import 'dart:convert';
import 'dart:io';

/// Converts USDA FoodData Central Foundation or FNDDS JSON into repeatable
/// Supabase SQL. It never contains keys or calls Supabase. Values are imported
/// per 100 g and the source dataset is recorded on every row.
void main(List<String> args) {
  final options = _options(args);
  final input = options['input'];
  final output = options['output'];
  final type = options['type'] ?? 'foundation';
  if (input == null || output == null) {
    stderr.writeln('Fehlende Argumente: --input <json> --output <sql>');
    exitCode = 64;
    return;
  }
  final file = File(input);
  if (!file.existsSync()) {
    stderr.writeln('Eingabedatei nicht gefunden: $input');
    exitCode = 66;
    return;
  }
  final document = jsonDecode(file.readAsStringSync());
  final key = type == 'fndds' ? 'SurveyFoods' : 'FoundationFoods';
  final rawFoods = document is Map ? document[key] : null;
  if (rawFoods is! List) {
    stderr.writeln('$key wurde nicht gefunden.');
    exitCode = 65;
    return;
  }
  final rows = <String>[];
  for (final raw in rawFoods.whereType<Map>()) {
    final id = raw['fdcId'];
    final name = raw['description']?.toString().trim();
    if (id == null || name == null || name.isEmpty) continue;
    final nutrients = _nutrients(raw['foodNutrients']);
    final calories = nutrients[1008];
    final protein = nutrients[1003];
    final carbohydrates = nutrients[1005];
    final fat = nutrients[1004];
    if (calories == null &&
        protein == null &&
        carbohydrates == null &&
        fat == null) {
      continue;
    }
    final sodium = nutrients[1093];
    final values = [
      _sql('usda-$type-$id'),
      _sql(name),
      'NULL',
      'NULL',
      '100',
      _number(calories),
      _number(protein),
      _number(carbohydrates),
      _number(fat),
      _number(nutrients[1079]),
      _number(nutrients[2000]),
      _number(sodium == null ? null : sodium * 2.5 / 1000),
      "'{}'",
      "'{}'",
      'NULL',
      _sql('usda_$type'),
      _sql('https://fdc.nal.usda.gov/download-datasets/'),
      _sql('USDA FoodData Central data release'),
      _sql('USDA FoodData Central'),
      _sql('imported'),
      'NULL',
      'false',
    ];
    rows.add('(${values.join(', ')})');
  }
  final sql = StringBuffer()
    ..writeln('-- Generated by tool/import_usda_foundation.dart.')
    ..writeln(
      '-- Source: USDA FoodData Central ${type == 'fndds' ? 'FNDDS' : 'Foundation Foods'}.',
    )
    ..writeln('-- Values are per 100 g; verify current terms before release.')
    ..writeln('begin;')
    ..writeln(
      'insert into public.foods (slug, name, brand, barcode, serving_grams, calories, protein,',
    )
    ..writeln(
      'carbohydrates, fat, fiber, sugar, salt, allergens, diet_tags, image_url, source,',
    )
    ..writeln(
      'source_url, source_license, source_attribution, data_quality, verified_at, is_premium) values',
    )
    ..writeln(rows.join(',\n'))
    ..writeln(
      'on conflict (slug) do update set name = excluded.name, serving_grams = excluded.serving_grams,',
    )
    ..writeln(
      'calories = excluded.calories, protein = excluded.protein, carbohydrates = excluded.carbohydrates,',
    )
    ..writeln(
      'fat = excluded.fat, fiber = excluded.fiber, sugar = excluded.sugar, salt = excluded.salt,',
    )
    ..writeln(
      'source = excluded.source, source_url = excluded.source_url, source_license = excluded.source_license,',
    )
    ..writeln(
      'source_attribution = excluded.source_attribution, data_quality = excluded.data_quality,',
    )
    ..writeln('updated_at = timezone(\'utc\', now());')
    ..writeln('commit;');
  final outputFile = File(output)..parent.createSync(recursive: true);
  outputFile.writeAsStringSync(sql.toString());
  stdout.writeln('Importdatei erstellt: $output');
  stdout.writeln('Lebensmittel importiert: ${rows.length}');
}

Map<String, String> _options(List<String> args) {
  final result = <String, String>{};
  for (var i = 0; i + 1 < args.length; i++) {
    if (args[i].startsWith('--')) result[args[i].substring(2)] = args[++i];
  }
  return result;
}

Map<int, double> _nutrients(Object? raw) {
  final result = <int, double>{};
  if (raw is! List) return result;
  for (final item in raw.whereType<Map>()) {
    final nutrient = item['nutrient'];
    final id = nutrient is Map ? int.tryParse('${nutrient['id']}') : null;
    final amount = _parseNumber(item['amount']);
    if (id != null && amount != null) result[id] = amount;
  }
  return result;
}

double? _parseNumber(Object? value) => value is num
    ? value.toDouble()
    : value is String
    ? double.tryParse(value.replaceAll(',', '.'))
    : null;

String _number(double? value) => value == null ? '0' : value.toStringAsFixed(3);
String _sql(String value) => "'${value.replaceAll("'", "''")}'";
